EXPIRY_PROFILE = {
    "instrument": "BANKNIFTY",
    "has_weekly_expiry": False,
    "weekly_expiry_weekday": None,
    "post_expiry_score_floor": 64,
    "pre_expiry_score_floor": 70,
    "expiry_vwap_distance_limit": 90,
    "opening_whipsaw_cutoff": "09:45",
    "midday_score_floor": 76,
    "late_session_score_floor": 74,
    "high_conviction_expiry_score": 76,
    "soft_expiry_score": 72,
    "expiry_opposite_pressure_score_floor": 78,
    "expiry_fast_decay_start": "13:00",
    "pre_expiry_watch_direction": None,
    "pre_expiry_watch_min_score": 0,
    "pre_expiry_watch_volume_signals": ["NORMAL", "STRONG"],
}
