EXPIRY_PROFILE = {
    "instrument": "NIFTY",
    "weekly_expiry_weekday": 1,
    "post_expiry_score_floor": 66,
    "pre_expiry_score_floor": 72,
    "expiry_vwap_distance_limit": 45,
    "opening_whipsaw_cutoff": "09:40",
    "midday_score_floor": 78,
    "late_session_score_floor": 76,
    "high_conviction_expiry_score": 76,
    "soft_expiry_score": 72,
    "expiry_opposite_pressure_score_floor": 78,
    "expiry_fast_decay_start": "13:00",
    "pre_expiry_watch_direction": "PE",
    "pre_expiry_watch_min_score": 85,
    "pre_expiry_watch_volume_signals": ["NORMAL", "STRONG"],
}
