def high_score_continuation_ready(
    *,
    price_vwap_aligned,
    volume_ok,
    score,
    high_continuation_min_score,
    oi_bias_ok,
    oi_trend_ok,
    build_up_ok,
    orb_extension_ok,
    candle_liquidity_ok,
    breakout_body_ok,
    breakout_structure_ok,
    ha_ok,
    far_from_vwap_ok,
    opposite_pressure_ok,
    continuation_regime_ok,
    adx_trade_ok,
    mtf_trade_ok,
    pressure_conflict_ok,
    focused_mode_ok,
):
    return all([
        price_vwap_aligned,
        volume_ok,
        score >= high_continuation_min_score,
        oi_bias_ok,
        oi_trend_ok,
        build_up_ok,
        orb_extension_ok,
        candle_liquidity_ok,
        breakout_body_ok,
        breakout_structure_ok,
        ha_ok,
        far_from_vwap_ok,
        opposite_pressure_ok,
        continuation_regime_ok,
        adx_trade_ok,
        mtf_trade_ok,
        pressure_conflict_ok,
        focused_mode_ok,
    ])


def fallback_continuation_ready(
    *,
    price_vwap_aligned,
    volume_ok,
    score,
    continuation_min_score,
    oi_bias_ok,
    oi_trend_ok,
    build_up_ok,
    candle_liquidity_ok,
    breakout_body_ok,
    breakout_structure_ok,
    ha_ok,
    opposite_pressure_ok,
    far_from_vwap_ok,
    opening_session,
    continuation_regime_ok,
    adx_ok,
    mtf_ok,
    pressure_conflict_ok,
    focused_mode_ok,
):
    return all([
        price_vwap_aligned,
        volume_ok,
        score >= continuation_min_score,
        oi_bias_ok,
        oi_trend_ok,
        build_up_ok,
        candle_liquidity_ok,
        breakout_body_ok,
        breakout_structure_ok,
        ha_ok,
        opposite_pressure_ok,
        far_from_vwap_ok,
        not opening_session,
        continuation_regime_ok,
        adx_ok,
        mtf_ok,
        pressure_conflict_ok,
        focused_mode_ok,
    ])
