EXPIRY_PROFILE = {
    "instrument": "SENSEX",
    "weekly_expiry_weekday": 3,
    "post_expiry_score_floor": 66,
    "pre_expiry_score_floor": 70,
    "expiry_vwap_distance_limit": 140,
    "opening_whipsaw_cutoff": "09:45",
    "midday_score_floor": 74,
    "late_session_score_floor": 72,
    "high_conviction_expiry_score": 74,
    "soft_expiry_score": 70,
    "expiry_opposite_pressure_score_floor": 74,
    "expiry_fast_decay_start": "13:15",
    "pre_expiry_watch_direction": None,
    "pre_expiry_watch_min_score": 0,
    "pre_expiry_watch_volume_signals": ["NORMAL", "STRONG"],
}
