BEGIN;

CREATE TABLE IF NOT EXISTS entry_decisions_1m (
  id BIGSERIAL PRIMARY KEY,
  ts TIMESTAMPTZ NOT NULL,
  instrument TEXT NOT NULL,
  watch_ts TIMESTAMPTZ,
  direction TEXT NOT NULL,
  decision TEXT NOT NULL,
  underlying_price NUMERIC(12,2),
  candle_open NUMERIC(12,2),
  candle_high NUMERIC(12,2),
  candle_low NUMERIC(12,2),
  candle_close NUMERIC(12,2),
  candle_volume BIGINT,
  trigger_price NUMERIC(12,2),
  invalidate_price NUMERIC(12,2),
  first_target_price NUMERIC(12,2),
  strike INTEGER,
  option_ltp NUMERIC(12,2),
  option_bid NUMERIC(12,2),
  option_ask NUMERIC(12,2),
  option_spread NUMERIC(12,2),
  score INTEGER,
  entry_score INTEGER,
  signal_type TEXT,
  signal_grade TEXT,
  confidence TEXT,
  watch_bucket TEXT,
  time_regime TEXT,
  minutes_since_watch INTEGER,
  reason TEXT,
  blockers_json JSONB,
  cautions_json JSONB,
  option_data_source TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (ts, instrument, watch_ts, direction)
);

COMMIT;
